package com.railwaysim.train;

import com.railwaysim.vehicle.VehicleLoadPolicy;
import com.railwaysim.vehicle.drivercab.DriverCabStateSnapshot;
import com.railwaysim.vehicle.external.ExternalTrainDirection;

public record TrainState(
    String id,
    String routeId,
    String serviceNo,
    String controlSessionState,
    String signalNetworkStatus,
    String powerNetworkStatus,
    String controlSessionReason,
    int linkId,
    String direction,
    double positionMeters,
    double speedMetersPerSecond,
    double lengthMeters,
    double headMileage,
    double tailMileage,
    double loadRate,
    double loadMassKg,
    String overloadStatus,
    int availableTractionCount,
    int availableBrakeCount,
    String vehicleProtectionReason,
    String status,
    String operationMode,
    boolean zeroSpeed,
    String doorState,
    String tractionState,
    String brakeState,
    String currentCollectionStatus,
    boolean tractionAvailable,
    boolean brakeAvailable,
    String selfCheckStatus,
    int faultLevel,
    String availableOperationMode,
    String dataQuality,
    String dynamicsState,
    String dynamicsConstraintReason,
    double speedLimitMetersPerSecond,
    double vehicleFaultSpeedLimitMetersPerSecond,
    double movementAuthorityDistanceMeters,
    double stationDistanceMeters,
    double stoppingDistanceMeters,
    double accelerationMetersPerSecondSquared,
    double tractionForceNewtons,
    double brakeForceNewtons,
    double regenBrakeForceNewtons,
    double railCurrentAmps,
    double tractionPowerWatts,
    double regenPowerWatts,
    double energyConsumedKwh,
    double energyRegeneratedKwh,
    String faultCode,
    String currentStationId,
    int dwellElapsedSeconds,
    String lastDepartureAt,
    DriverCabStateSnapshot driverCabState
) {
    public TrainState(
        String id,
        String routeId,
        String serviceNo,
        String controlSessionState,
        String signalNetworkStatus,
        String powerNetworkStatus,
        String controlSessionReason,
        int linkId,
        String direction,
        double positionMeters,
        double speedMetersPerSecond,
        double lengthMeters,
        double headMileage,
        double tailMileage,
        double loadRate,
        double loadMassKg,
        String overloadStatus,
        int availableTractionCount,
        int availableBrakeCount,
        String vehicleProtectionReason,
        String status,
        String operationMode,
        boolean zeroSpeed,
        String doorState,
        String tractionState,
        String brakeState,
        String currentCollectionStatus,
        boolean tractionAvailable,
        boolean brakeAvailable,
        String selfCheckStatus,
        int faultLevel,
        String availableOperationMode,
        String dataQuality,
        String dynamicsState,
        String dynamicsConstraintReason,
        double speedLimitMetersPerSecond,
        double vehicleFaultSpeedLimitMetersPerSecond,
        double movementAuthorityDistanceMeters,
        double stationDistanceMeters,
        double stoppingDistanceMeters,
        double accelerationMetersPerSecondSquared,
        double tractionForceNewtons,
        double brakeForceNewtons,
        double regenBrakeForceNewtons,
        double railCurrentAmps,
        double tractionPowerWatts,
        double regenPowerWatts,
        double energyConsumedKwh,
        double energyRegeneratedKwh,
        String faultCode,
        String currentStationId,
        int dwellElapsedSeconds,
        String lastDepartureAt
    ) {
        this(
            id,
            routeId,
            serviceNo,
            controlSessionState,
            signalNetworkStatus,
            powerNetworkStatus,
            controlSessionReason,
            linkId,
            direction,
            positionMeters,
            speedMetersPerSecond,
            lengthMeters,
            headMileage,
            tailMileage,
            loadRate,
            loadMassKg,
            overloadStatus,
            availableTractionCount,
            availableBrakeCount,
            vehicleProtectionReason,
            status,
            operationMode,
            zeroSpeed,
            doorState,
            tractionState,
            brakeState,
            currentCollectionStatus,
            tractionAvailable,
            brakeAvailable,
            selfCheckStatus,
            faultLevel,
            availableOperationMode,
            dataQuality,
            dynamicsState,
            dynamicsConstraintReason,
            speedLimitMetersPerSecond,
            vehicleFaultSpeedLimitMetersPerSecond,
            movementAuthorityDistanceMeters,
            stationDistanceMeters,
            stoppingDistanceMeters,
            accelerationMetersPerSecondSquared,
            tractionForceNewtons,
            brakeForceNewtons,
            regenBrakeForceNewtons,
            railCurrentAmps,
            tractionPowerWatts,
            regenPowerWatts,
            energyConsumedKwh,
            energyRegeneratedKwh,
            faultCode,
            currentStationId,
            dwellElapsedSeconds,
            lastDepartureAt,
            null
        );
    }

    public TrainState(
        String id,
        String routeId,
        String serviceNo,
        double positionMeters,
        double speedMetersPerSecond,
        double lengthMeters,
        double headMileage,
        double tailMileage,
        double loadRate,
        String status,
        String operationMode,
        boolean zeroSpeed,
        String doorState,
        String tractionState,
        String brakeState,
        String currentCollectionStatus,
        boolean tractionAvailable,
        boolean brakeAvailable,
        String selfCheckStatus,
        int faultLevel,
        String availableOperationMode,
        String dataQuality,
        String dynamicsState,
        String dynamicsConstraintReason,
        double speedLimitMetersPerSecond,
        double movementAuthorityDistanceMeters,
        double stationDistanceMeters,
        double stoppingDistanceMeters,
        double accelerationMetersPerSecondSquared,
        double tractionForceNewtons,
        double brakeForceNewtons,
        double regenBrakeForceNewtons,
        double railCurrentAmps,
        double tractionPowerWatts,
        double regenPowerWatts,
        double energyConsumedKwh,
        double energyRegeneratedKwh,
        String faultCode
    ) {
        this(
            id,
            routeId,
            serviceNo,
            ExternalTrainControlSessionState.IN_SERVICE.name(),
            "ATTACHED",
            "ATTACHED",
            "EXTERNAL_CONTROL_IN_SERVICE",
            0,
            ExternalTrainDirection.UNKNOWN.name(),
            positionMeters,
            speedMetersPerSecond,
            lengthMeters,
            headMileage,
            tailMileage,
            loadRate,
            VehicleLoadPolicy.loadMassFromRate(loadRate),
            VehicleLoadPolicy.overloadStatus(VehicleLoadPolicy.loadMassFromRate(loadRate)),
            VehicleLoadPolicy.NOMINAL_TRACTION_UNITS,
            VehicleLoadPolicy.NOMINAL_BRAKE_UNITS,
            VehicleLoadPolicy.vehicleProtectionReason(
                VehicleLoadPolicy.overloadStatus(VehicleLoadPolicy.loadMassFromRate(loadRate))
            ),
            status,
            operationMode,
            zeroSpeed,
            doorState,
            tractionState,
            brakeState,
            currentCollectionStatus,
            tractionAvailable,
            brakeAvailable,
            selfCheckStatus,
            faultLevel,
            availableOperationMode,
            dataQuality,
            dynamicsState,
            dynamicsConstraintReason,
            speedLimitMetersPerSecond,
            0,
            movementAuthorityDistanceMeters,
            stationDistanceMeters,
            stoppingDistanceMeters,
            accelerationMetersPerSecondSquared,
            tractionForceNewtons,
            brakeForceNewtons,
            regenBrakeForceNewtons,
            railCurrentAmps,
            tractionPowerWatts,
            regenPowerWatts,
            energyConsumedKwh,
            energyRegeneratedKwh,
            faultCode,
            null,
            0,
            null,
            null
        );
    }

    public TrainState(
        String id,
        String routeId,
        String serviceNo,
        double positionMeters,
        double speedMetersPerSecond,
        double lengthMeters,
        double headMileage,
        double tailMileage,
        double loadRate,
        String status,
        String operationMode,
        boolean zeroSpeed,
        String doorState,
        String tractionState,
        String brakeState,
        String currentCollectionStatus,
        boolean tractionAvailable,
        boolean brakeAvailable,
        String selfCheckStatus,
        int faultLevel,
        String availableOperationMode,
        String dataQuality,
        String dynamicsState,
        String dynamicsConstraintReason,
        double speedLimitMetersPerSecond,
        double movementAuthorityDistanceMeters,
        double stationDistanceMeters,
        double stoppingDistanceMeters,
        double accelerationMetersPerSecondSquared,
        double tractionForceNewtons,
        double brakeForceNewtons,
        double regenBrakeForceNewtons,
        double railCurrentAmps,
        double tractionPowerWatts,
        double regenPowerWatts,
        double energyConsumedKwh,
        double energyRegeneratedKwh,
        String faultCode,
        String currentStationId,
        int dwellElapsedSeconds,
        String lastDepartureAt
    ) {
        this(
            id,
            routeId,
            serviceNo,
            ExternalTrainControlSessionState.IN_SERVICE.name(),
            "ATTACHED",
            "ATTACHED",
            "EXTERNAL_CONTROL_IN_SERVICE",
            0,
            ExternalTrainDirection.UNKNOWN.name(),
            positionMeters,
            speedMetersPerSecond,
            lengthMeters,
            headMileage,
            tailMileage,
            loadRate,
            VehicleLoadPolicy.loadMassFromRate(loadRate),
            VehicleLoadPolicy.overloadStatus(VehicleLoadPolicy.loadMassFromRate(loadRate)),
            VehicleLoadPolicy.NOMINAL_TRACTION_UNITS,
            VehicleLoadPolicy.NOMINAL_BRAKE_UNITS,
            VehicleLoadPolicy.vehicleProtectionReason(
                VehicleLoadPolicy.overloadStatus(VehicleLoadPolicy.loadMassFromRate(loadRate))
            ),
            status,
            operationMode,
            zeroSpeed,
            doorState,
            tractionState,
            brakeState,
            currentCollectionStatus,
            tractionAvailable,
            brakeAvailable,
            selfCheckStatus,
            faultLevel,
            availableOperationMode,
            dataQuality,
            dynamicsState,
            dynamicsConstraintReason,
            speedLimitMetersPerSecond,
            0,
            movementAuthorityDistanceMeters,
            stationDistanceMeters,
            stoppingDistanceMeters,
            accelerationMetersPerSecondSquared,
            tractionForceNewtons,
            brakeForceNewtons,
            regenBrakeForceNewtons,
            railCurrentAmps,
            tractionPowerWatts,
            regenPowerWatts,
            energyConsumedKwh,
            energyRegeneratedKwh,
            faultCode,
            currentStationId,
            dwellElapsedSeconds,
            lastDepartureAt
        );
    }

    public TrainState(
        String id,
        String routeId,
        String serviceNo,
        double positionMeters,
        double speedMetersPerSecond,
        double lengthMeters,
        double headMileage,
        double tailMileage,
        double loadRate,
        double loadMassKg,
        String overloadStatus,
        int availableTractionCount,
        int availableBrakeCount,
        String vehicleProtectionReason,
        String status,
        String operationMode,
        boolean zeroSpeed,
        String doorState,
        String tractionState,
        String brakeState,
        String currentCollectionStatus,
        boolean tractionAvailable,
        boolean brakeAvailable,
        String selfCheckStatus,
        int faultLevel,
        String availableOperationMode,
        String dataQuality,
        String dynamicsState,
        String dynamicsConstraintReason,
        double speedLimitMetersPerSecond,
        double movementAuthorityDistanceMeters,
        double stationDistanceMeters,
        double stoppingDistanceMeters,
        double accelerationMetersPerSecondSquared,
        double tractionForceNewtons,
        double brakeForceNewtons,
        double regenBrakeForceNewtons,
        double railCurrentAmps,
        double tractionPowerWatts,
        double regenPowerWatts,
        double energyConsumedKwh,
        double energyRegeneratedKwh,
        String faultCode
    ) {
        this(
            id,
            routeId,
            serviceNo,
            ExternalTrainControlSessionState.IN_SERVICE.name(),
            "ATTACHED",
            "ATTACHED",
            "EXTERNAL_CONTROL_IN_SERVICE",
            0,
            ExternalTrainDirection.UNKNOWN.name(),
            positionMeters,
            speedMetersPerSecond,
            lengthMeters,
            headMileage,
            tailMileage,
            loadRate,
            loadMassKg,
            overloadStatus,
            availableTractionCount,
            availableBrakeCount,
            vehicleProtectionReason,
            status,
            operationMode,
            zeroSpeed,
            doorState,
            tractionState,
            brakeState,
            currentCollectionStatus,
            tractionAvailable,
            brakeAvailable,
            selfCheckStatus,
            faultLevel,
            availableOperationMode,
            dataQuality,
            dynamicsState,
            dynamicsConstraintReason,
            speedLimitMetersPerSecond,
            0,
            movementAuthorityDistanceMeters,
            stationDistanceMeters,
            stoppingDistanceMeters,
            accelerationMetersPerSecondSquared,
            tractionForceNewtons,
            brakeForceNewtons,
            regenBrakeForceNewtons,
            railCurrentAmps,
            tractionPowerWatts,
            regenPowerWatts,
            energyConsumedKwh,
            energyRegeneratedKwh,
            faultCode,
            null,
            0,
            null,
            null
        );
    }

    public TrainState(
        String id,
        String routeId,
        String serviceNo,
        double positionMeters,
        double speedMetersPerSecond,
        double lengthMeters,
        double headMileage,
        double tailMileage,
        double loadRate,
        double loadMassKg,
        String overloadStatus,
        int availableTractionCount,
        int availableBrakeCount,
        String vehicleProtectionReason,
        String status,
        String operationMode,
        boolean zeroSpeed,
        String doorState,
        String tractionState,
        String brakeState,
        String currentCollectionStatus,
        boolean tractionAvailable,
        boolean brakeAvailable,
        String selfCheckStatus,
        int faultLevel,
        String availableOperationMode,
        String dataQuality,
        String dynamicsState,
        String dynamicsConstraintReason,
        double speedLimitMetersPerSecond,
        double movementAuthorityDistanceMeters,
        double stationDistanceMeters,
        double stoppingDistanceMeters,
        double accelerationMetersPerSecondSquared,
        double tractionForceNewtons,
        double brakeForceNewtons,
        double regenBrakeForceNewtons,
        double railCurrentAmps,
        double tractionPowerWatts,
        double regenPowerWatts,
        double energyConsumedKwh,
        double energyRegeneratedKwh,
        String faultCode,
        String currentStationId,
        int dwellElapsedSeconds,
        String lastDepartureAt
    ) {
        this(
            id,
            routeId,
            serviceNo,
            ExternalTrainControlSessionState.IN_SERVICE.name(),
            "ATTACHED",
            "ATTACHED",
            "EXTERNAL_CONTROL_IN_SERVICE",
            0,
            ExternalTrainDirection.UNKNOWN.name(),
            positionMeters,
            speedMetersPerSecond,
            lengthMeters,
            headMileage,
            tailMileage,
            loadRate,
            loadMassKg,
            overloadStatus,
            availableTractionCount,
            availableBrakeCount,
            vehicleProtectionReason,
            status,
            operationMode,
            zeroSpeed,
            doorState,
            tractionState,
            brakeState,
            currentCollectionStatus,
            tractionAvailable,
            brakeAvailable,
            selfCheckStatus,
            faultLevel,
            availableOperationMode,
            dataQuality,
            dynamicsState,
            dynamicsConstraintReason,
            speedLimitMetersPerSecond,
            0,
            movementAuthorityDistanceMeters,
            stationDistanceMeters,
            stoppingDistanceMeters,
            accelerationMetersPerSecondSquared,
            tractionForceNewtons,
            brakeForceNewtons,
            regenBrakeForceNewtons,
            railCurrentAmps,
            tractionPowerWatts,
            regenPowerWatts,
            energyConsumedKwh,
            energyRegeneratedKwh,
            faultCode,
            currentStationId,
            dwellElapsedSeconds,
            lastDepartureAt
        );
    }

    /** 为快照创建显示用副本：DOWN列车位置镜像(L-pos)，UP不变。 */
    public TrainState forDisplay(double lineLengthMeters) {
        if (!"DOWN".equalsIgnoreCase(direction) || lineLengthMeters <= 0) return this;
        double pos = Math.max(0, lineLengthMeters - positionMeters);
        double tail = Math.max(0, pos - lengthMeters);
        return new TrainState(id, routeId, serviceNo,
            controlSessionState, signalNetworkStatus, powerNetworkStatus,
            controlSessionReason, linkId, direction,
            pos, speedMetersPerSecond, lengthMeters, pos, tail,
            loadRate, loadMassKg, overloadStatus,
            availableTractionCount, availableBrakeCount,
            vehicleProtectionReason, status, operationMode, zeroSpeed,
            doorState, tractionState, brakeState, currentCollectionStatus,
            tractionAvailable, brakeAvailable, selfCheckStatus,
            faultLevel, availableOperationMode, dataQuality,
            dynamicsState, dynamicsConstraintReason,
            speedLimitMetersPerSecond, vehicleFaultSpeedLimitMetersPerSecond,
            movementAuthorityDistanceMeters, stationDistanceMeters, stoppingDistanceMeters,
            accelerationMetersPerSecondSquared,
            tractionForceNewtons, brakeForceNewtons, regenBrakeForceNewtons,
            railCurrentAmps, tractionPowerWatts, regenPowerWatts,
            energyConsumedKwh, energyRegeneratedKwh,
            faultCode, currentStationId, dwellElapsedSeconds, lastDepartureAt,
            driverCabState);
    }
}
