package com.railwaysim.train;

import com.railwaysim.vehicle.VehicleLoadPolicy;

public record TrainState(
    String id,
    String routeId,
    String serviceNo,
    double positionMeters,
    double speedMetersPerSecond,
    double lengthMeters,
    double headMileage,
    double tailMileage,
    double loadRate,
    double loadMassKg,
    String overloadStatus,
    int availableTractionCount,
    int availableBrakeCount,
    String vehicleProtectionReason,
    String status,
    String operationMode,
    boolean zeroSpeed,
    String doorState,
    String tractionState,
    String brakeState,
    String currentCollectionStatus,
    boolean tractionAvailable,
    boolean brakeAvailable,
    String selfCheckStatus,
    int faultLevel,
    String availableOperationMode,
    String dataQuality,
    String dynamicsState,
    String dynamicsConstraintReason,
    double speedLimitMetersPerSecond,
    double movementAuthorityDistanceMeters,
    double stationDistanceMeters,
    double stoppingDistanceMeters,
    double accelerationMetersPerSecondSquared,
    double tractionForceNewtons,
    double brakeForceNewtons,
    double regenBrakeForceNewtons,
    double railCurrentAmps,
    double tractionPowerWatts,
    double regenPowerWatts,
    double energyConsumedKwh,
    double energyRegeneratedKwh,
    String faultCode,
    String currentStationId,
    int dwellElapsedSeconds,
    String lastDepartureAt
) {
    public TrainState(
        String id,
        String routeId,
        String serviceNo,
        double positionMeters,
        double speedMetersPerSecond,
        double lengthMeters,
        double headMileage,
        double tailMileage,
        double loadRate,
        String status,
        String operationMode,
        boolean zeroSpeed,
        String doorState,
        String tractionState,
        String brakeState,
        String currentCollectionStatus,
        boolean tractionAvailable,
        boolean brakeAvailable,
        String selfCheckStatus,
        int faultLevel,
        String availableOperationMode,
        String dataQuality,
        String dynamicsState,
        String dynamicsConstraintReason,
        double speedLimitMetersPerSecond,
        double movementAuthorityDistanceMeters,
        double stationDistanceMeters,
        double stoppingDistanceMeters,
        double accelerationMetersPerSecondSquared,
        double tractionForceNewtons,
        double brakeForceNewtons,
        double regenBrakeForceNewtons,
        double railCurrentAmps,
        double tractionPowerWatts,
        double regenPowerWatts,
        double energyConsumedKwh,
        double energyRegeneratedKwh,
        String faultCode
    ) {
        this(
            id,
            routeId,
            serviceNo,
            positionMeters,
            speedMetersPerSecond,
            lengthMeters,
            headMileage,
            tailMileage,
            loadRate,
            VehicleLoadPolicy.loadMassFromRate(loadRate),
            VehicleLoadPolicy.overloadStatus(VehicleLoadPolicy.loadMassFromRate(loadRate)),
            VehicleLoadPolicy.NOMINAL_TRACTION_UNITS,
            VehicleLoadPolicy.NOMINAL_BRAKE_UNITS,
            VehicleLoadPolicy.vehicleProtectionReason(
                VehicleLoadPolicy.overloadStatus(VehicleLoadPolicy.loadMassFromRate(loadRate))
            ),
            status,
            operationMode,
            zeroSpeed,
            doorState,
            tractionState,
            brakeState,
            currentCollectionStatus,
            tractionAvailable,
            brakeAvailable,
            selfCheckStatus,
            faultLevel,
            availableOperationMode,
            dataQuality,
            dynamicsState,
            dynamicsConstraintReason,
            speedLimitMetersPerSecond,
            movementAuthorityDistanceMeters,
            stationDistanceMeters,
            stoppingDistanceMeters,
            accelerationMetersPerSecondSquared,
            tractionForceNewtons,
            brakeForceNewtons,
            regenBrakeForceNewtons,
            railCurrentAmps,
            tractionPowerWatts,
            regenPowerWatts,
            energyConsumedKwh,
            energyRegeneratedKwh,
            faultCode,
            null,
            0,
            null
        );
    }
}
