package com.railwaysim.signal.vehicle;

import com.railwaysim.train.TrainState;

public record VehicleSignalStatus(
    String trainId,
    String controlSessionState,
    String signalNetworkStatus,
    String powerNetworkStatus,
    String controlSessionReason,
    int linkId,
    String direction,
    double headMileage,
    double tailMileage,
    double speedMetersPerSecond,
    boolean zeroSpeed,
    String doorState,
    boolean tractionAvailable,
    boolean brakeAvailable,
    String currentCollectionStatus,
    double loadMassKg,
    String overloadStatus,
    int availableTractionCount,
    int availableBrakeCount,
    String vehicleProtectionReason,
    String operationMode,
    String selfCheckStatus,
    int faultLevel,
    String availableOperationMode,
    String faultCode,
    String dynamicsState,
    String dynamicsConstraintReason,
    double vehicleFaultSpeedLimitMetersPerSecond,
    String dataQuality,
    SignalDriverConsoleState driverConsoleState
) {
    public static VehicleSignalStatus from(TrainState train) {
        return new VehicleSignalStatus(
            train.id(),
            train.controlSessionState(),
            train.signalNetworkStatus(),
            train.powerNetworkStatus(),
            train.controlSessionReason(),
            train.linkId(),
            train.direction(),
            train.headMileage(),
            train.tailMileage(),
            train.speedMetersPerSecond(),
            train.zeroSpeed(),
            train.doorState(),
            train.tractionAvailable(),
            train.brakeAvailable(),
            train.currentCollectionStatus(),
            train.loadMassKg(),
            train.overloadStatus(),
            train.availableTractionCount(),
            train.availableBrakeCount(),
            train.vehicleProtectionReason(),
            train.operationMode(),
            train.selfCheckStatus(),
            train.faultLevel(),
            train.availableOperationMode(),
            train.faultCode(),
            train.dynamicsState(),
            train.dynamicsConstraintReason(),
            train.vehicleFaultSpeedLimitMetersPerSecond(),
            train.dataQuality(),
            SignalDriverConsoleState.from(train)
        );
    }
}
