package com.railwaysim.vehicle;

public record TrainStateReport(
    String trainId,
    String operationMode,
    boolean doorClosed,
    String doorState,
    String tractionState,
    String brakeState,
    String currentCollectionStatus,
    boolean tractionAvailable,
    boolean brakeAvailable,
    String selfCheckStatus,
    int faultLevel,
    String availableOperationMode,
    String dataQuality,
    double loadMassKg,
    String overloadStatus,
    int availableTractionCount,
    int availableBrakeCount,
    String vehicleProtectionReason,
    String dynamicsState,
    String dynamicsConstraintReason,
    double speedLimitMetersPerSecond,
    double movementAuthorityDistanceMeters,
    double stationDistanceMeters,
    double stoppingDistanceMeters,
    double tractionCommand,
    double brakeCommand,
    boolean emergencyBrakeCommand,
    double railVoltage,
    double powerAvailableWatts,
    String faultCode
) {
    public TrainStateReport(
        String trainId,
        String operationMode,
        boolean doorClosed,
        String doorState,
        String tractionState,
        String brakeState,
        String currentCollectionStatus,
        boolean tractionAvailable,
        boolean brakeAvailable,
        String selfCheckStatus,
        int faultLevel,
        String availableOperationMode,
        String dataQuality,
        String dynamicsState,
        String dynamicsConstraintReason,
        double speedLimitMetersPerSecond,
        double movementAuthorityDistanceMeters,
        double stationDistanceMeters,
        double stoppingDistanceMeters,
        double tractionCommand,
        double brakeCommand,
        boolean emergencyBrakeCommand,
        double railVoltage,
        double powerAvailableWatts,
        String faultCode
    ) {
        this(
            trainId,
            operationMode,
            doorClosed,
            doorState,
            tractionState,
            brakeState,
            currentCollectionStatus,
            tractionAvailable,
            brakeAvailable,
            selfCheckStatus,
            faultLevel,
            availableOperationMode,
            dataQuality,
            0,
            "NORMAL",
            VehicleLoadPolicy.NOMINAL_TRACTION_UNITS,
            VehicleLoadPolicy.NOMINAL_BRAKE_UNITS,
            "NONE",
            dynamicsState,
            dynamicsConstraintReason,
            speedLimitMetersPerSecond,
            movementAuthorityDistanceMeters,
            stationDistanceMeters,
            stoppingDistanceMeters,
            tractionCommand,
            brakeCommand,
            emergencyBrakeCommand,
            railVoltage,
            powerAvailableWatts,
            faultCode
        );
    }
}
